import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRtl: boolean;
  t: (key: string) => string;
}

// Complete translation map for all UI elements
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.bridal': 'Bridal',
    'nav.evening': 'Evening',
    'nav.rentals': 'Rentals',
    'nav.about': 'Our Story',
    'nav.contact': 'Contact',
    'nav.timeline': 'Timeline',
    'nav.style_quiz': 'Style Quiz',
    'nav.jewelry': 'Fine Jewelry',
    'nav.accessories': 'Accessories',
    'nav.gallery': 'Gallery',
    'nav.alterations': 'Alterations',
    'nav.faq': 'FAQ',
    'nav.appointment': 'Private Viewing',

    // Categories
    'cat.bridal': 'Bridal',
    'cat.evening': 'Evening',
    'cat.rentals': 'Rentals',
    'cat.jewelry': 'Fine Jewelry',
    'cat.collection': 'The Collection',
    'cat.gala': 'Gala Gowns',
    'cat.service': 'Premium Service',
    'cat.majestic': 'Majestic Selection',
    'cat.all': 'All Designs',
    'cat.bridal_title': 'Bridal Collection',
    'cat.evening_title': 'Evening Gowns',
    'cat.rental_title': 'Premium Rentals',
    'cat.jewelry_title': 'Majestic Jewelry',
    'cat.accessories_title': 'Accessories',
    'cat.subtitle': 'Exquisite silhouettes and premium fabrics selected for the modern visionary.',

    // Hero
    'hero.title': 'Reverie & Essence',
    'hero.subtitle': "Sharjah's Premier Couture Atelier",
    'hero.discover': 'Discover',

    // Salon chapters
    'chapter.atelier': "L'Atelier",
    'chapter.silhouettes': 'Les Silhouettes',
    'chapter.savoir_faire': 'Le Savoir-Faire',
    'invitation.line': 'Continue the conversation — request a private viewing.',
    'invitation.cta': 'Request a Private Viewing',
    'nav.private_viewing': 'Private Viewing',
    'silhouettes.look': 'Look',
    'silhouettes.enquire': 'Enquire',

    // Salon homepage
    'atelier.heading': 'Mastering The Legacy Icon',
    'atelier.quote': 'It begins with a tension — the architecture of Mikado silk against the whisper of French tulle.',
    'atelier.body': 'Since 2011 our Sharjah atelier has cut by hand, fitted by eye, and finished by patience. Fewer gowns, finer gowns.',
    'savoir.p1': 'Cut less, cut better. We drape Mikado silk and French tulle by hand, letting the fabric decide the line.',
    'savoir.p2': 'Every discipline of the maison — bridal, evening, rental — begins at the same table: fabric, thread, patience.',
    'disciplines.bridal': 'Gowns made once, for one day, forever.',
    'disciplines.evening': 'Red-carpet presence, tailored to the moment.',
    'disciplines.rentals': 'Couture for a night, kept flawless.',
    'disciplines.discover': 'Discover',
    'invitation.heading': 'Experience The Riman Touch',
    'invitation.contact_line': 'Sharjah · By Appointment Only',

    // Couture Motion — Philosophy & Lookbook
    'philosophy.eyebrow': 'The Philosophy',
    'philosophy.statement': 'Every gown begins as a whisper — a sketch, a fabric, a dream. Our artisans cut less, and cut better.',
    'philosophy.stat_years': 'Years of Craft',
    'philosophy.stat_fibres': 'Natural Fibres',
    'philosophy.stat_brides': 'Bespoke Brides',
    'lookbook.eyebrow': 'The Lookbook',
    'lookbook.heading': 'Silhouettes in Motion',
    'lookbook.cta': 'View the Collection',

    // CTAs
    'cta.explore': 'Explore Collection',
    'cta.viewing': 'Request A Private Viewing',
    'cta.appointment': 'Book Appointment',
    'cta.view_all': 'View All',
    'cta.discover_all': 'Discover All',

    // Heritage section
    'heritage.title': 'Our Heritage',
    'heritage.heading': 'The Riman Legacy',

    // Curated / Featured
    'curated.eyebrow': 'Curated Style',
    'curated.heading': 'Featured Designs',

    // Featured In
    'featured_in.title': 'As Featured In',
    'featured_in.trusted': "Trusted by the world's leading fashion publications",

    // Jewelry section
    'jewelry.eyebrow': 'Riman Fine Jewelry',
    'jewelry.heading': 'The Golden Bespoke Collection',

    // Experience / Consultation banner
    'experience.heading': 'Experience The Riman Touch',
    'experience.desc': 'Book a complimentary private consultation at our Sharjah atelier. Our master stylists will guide you through our collection and help you find the silhouette of your dreams.',
    'experience.cta': 'Book Your Private Viewing',
    'experience.bridal': 'Bridal Couture',
    'experience.evening': 'Evening Wear',
    'experience.jewelry': 'Fine Jewelry',

    // About
    'about.title': 'The Riman Legacy',
    'about.hero_subtitle': 'Est. 2012 — Sharjah, UAE',
    'about.hero_title': 'The Riman Heritage',
    'about.pillar_1_title': 'Ethical Craft',
    'about.pillar_1_desc': 'We work exclusively with fair-trade silk suppliers and master artisans.',
    'about.pillar_2_title': 'Heritage Ties',
    'about.pillar_2_desc': 'Deeply rooted in Emirati culture using traditional techniques like Tali.',
    'about.pillar_3_title': 'Infinite Service',
    'about.pillar_3_desc': 'A lifetime of care for your Riman investments.',
    'about.pillars_heading': 'The Atelier Pillars',
    'about.team_eyebrow': 'The Visionaries',
    'about.team_heading': 'The Riman Collective',

    // Terms
    'terms.title': 'Terms of Service',
    'terms.subtitle': 'Boutique policies',
    'terms.last_updated': 'Last updated: July 28, 2026',
    'terms.section_1_title': '1. Introduction',
    'terms.section_1_body': 'Welcome to Atelier Riman. These Terms of Service govern your use of our website and services. By accessing or purchasing from our site, you agree to be bound by these terms. If you do not agree, please refrain from using our services.',
    'terms.section_2_title': '2. Account & Registration',
    'terms.section_2_body': 'When creating an account, you must provide accurate and complete information. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. We reserve the right to suspend or terminate accounts for violations of these terms.',
    'terms.section_3_title': '3. Products & Pricing',
    'terms.section_3_body': 'All prices are listed in AED (United Arab Emirates Dirham) unless otherwise stated. We strive for accuracy but cannot guarantee that all product images or descriptions are error-free. We reserve the right to correct errors, modify pricing, or discontinue items without prior notice.',
    'terms.section_4_title': '4. Orders & Payment',
    'terms.section_4_body': 'Orders are processed through Stripe, a secure third-party payment processor. By placing an order, you authorise us to charge the applicable amount. We reserve the right to refuse or cancel orders at our discretion, including those with pricing errors or suspected fraud.',
    'terms.section_5_title': '5. Shipping & Delivery',
    'terms.section_5_body': 'We ship to addresses within the UAE and select international destinations. Delivery times are estimates and not guaranteed. Risk of loss passes to you upon delivery. Custom or made-to-order pieces may require extended production timelines.',
    'terms.section_6_title': '6. Returns, Exchanges & Rentals',
    'terms.section_6_body': 'Sale items may be returned within 14 days of delivery in original condition. Rental items are subject to a separate rental agreement with deposit, duration, and damage terms. Alterations are final sale unless faulty. Contact our atelier for return authorisation.',
    'terms.section_7_title': '7. Intellectual Property',
    'terms.section_7_body': 'All content on this site — including designs, images, logos, text, and graphics — is the exclusive property of Atelier Riman and is protected by UAE and international copyright laws. You may not reproduce, distribute, or modify any content without our written consent.',
    'terms.section_8_title': '8. Limitation of Liability',
    'terms.section_8_body': 'Atelier Riman shall not be liable for indirect, incidental, or consequential damages arising from your use of our site or products. Our total liability is limited to the amount you paid for the product in question. This does not affect your statutory rights.',
    'terms.section_9_title': '9. Governing Law',
    'terms.section_9_body': 'These terms are governed by the laws of the United Arab Emirates, Emirate of Sharjah. Any disputes shall be resolved through amicable negotiation or, failing that, in the courts of Sharjah.',
    'terms.contact_title': 'Contact',
    'terms.contact_body': 'For questions about these terms, please reach out to our team:',
    'terms.contact_info': 'Atelier Riman — Al Zahra St, Sharjah, UAE — hello@riman.ae',

    // Privacy
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Your data security',
    'privacy.last_updated': 'Last updated: July 28, 2026',
    'privacy.section_1_title': '1. Information We Collect',
    'privacy.section_1_body': 'We collect personal information you provide when placing an order, creating an account, or contacting us — including your name, email, phone number, shipping address, and payment details. We also collect browsing data such as pages visited and device information.',
    'privacy.section_2_title': '2. How We Use Your Information',
    'privacy.section_2_body': 'We use your data to process orders, communicate order status, send service-related emails (not marketing), improve our website, and comply with legal obligations. We do not sell your personal information to third parties.',
    'privacy.section_3_title': '3. Payment Processing',
    'privacy.section_3_body': 'All payments are handled by Stripe, a PCI-DSS compliant payment processor. We do not store full credit card numbers on our servers. Stripe receives your payment data directly and processes it under their privacy policy.',
    'privacy.section_4_title': '4. Data Sharing',
    'privacy.section_4_body': 'We may share your information with trusted third parties who help us operate our business — including shipping carriers, payment processors, and IT service providers. These parties are contractually bound to protect your data.',
    'privacy.section_5_title': '5. Cookies',
    'privacy.section_5_body': 'Our site uses essential cookies for functionality. We also use analytics cookies (Fathom, Plausible) to understand site traffic without tracking individual users. You can control cookie preferences through your browser settings.',
    'privacy.section_6_title': '6. Your Rights',
    'privacy.section_6_body': 'You have the right to access, correct, or delete your personal data held by us. You may also object to or restrict certain processing. To exercise these rights, contact us at the address below. We will respond within 30 days.',
    'privacy.section_7_title': '7. Data Security',
    'privacy.section_7_body': 'We implement appropriate technical and organisational measures to protect your data, including SSL/TLS encryption, access controls, and regular security reviews. However, no method of transmission over the internet is 100% secure.',
    'privacy.contact_title': 'Contact',
    'privacy.contact_body': 'For privacy-related inquiries or to exercise your rights:',
    'privacy.contact_info': 'Atelier Riman — Al Zahra St, Sharjah, UAE — hello@riman.ae',

    // Product
    'product.added': 'Added',
    'product.quick_add': 'Quick Add',
    'product.view_details': 'View Full Details',
    'product.in_wishlist': 'In Wishlist',
    'product.add_wishlist': 'Add to Wishlist',
    'product.purchase': 'Purchase',
    'product.rent': 'Rent',
    'product.not_found': 'Design Not Found',
    'product.back_to_collection': 'Back to Collection',
    'product.limited_edition': 'Limited Edition',
    'product.purchase_value': 'Purchase Value',
    'product.rental_7day': '4-Day Premium Rental',
    'product.rental_includes': 'Dry Clean & Insurance Included',
    'product.refundable_deposit': '+ Refundable Deposit Required',
    'product.select_size_label': 'Select Size',
    'product.size_guide': 'Size Guide',
    'product.book_rental': 'Book Rental',
    'product.add_to_collection': 'Add to Collection',
    'product.reserve_viewing': 'Reserve a Private Viewing',
    'product.error_no_date': 'Please select a preferred rental date.',
    'product.error_no_size': 'Please select your size.',
    'product.rental_availability': 'Rental Availability',
    'product.fast_booking': 'Fast-Booking Recommended',
    'product.select_date_hint': 'Select a date to check 7-day premier hire availability.',
    'product.selected_date': 'Selected Date',
    'product.specifications': 'Specifications',
    'product.fabric': 'Fabric Composition',
    'product.designer': 'Designer',
    'product.style_elements': 'Style Elements',
    'product.couture_care': 'Couture Care',
    'product.cleaning_included': 'Cleaning Included',
    'product.secure_delivery': 'Secure Delivery',
    'product.uae_gcc': 'UAE & GCC',
    'product.bespoke_fit': 'Bespoke Fit',
    'product.custom_tailoring': 'Custom Tailoring',
    'product.artistry_essence': 'Artistry & Essence',
    'product.client_reflections': 'Client Reflections',
    'product.leave_reflection': 'Leave a Reflection',
    'product.reflection_curated': 'Your reflection has been curated.',
    'product.write_another': 'Write another',
    'product.your_name': 'Your Name',
    'product.your_reflection': 'Your Reflection',
    'product.submit_review': 'Submit Review',
    'product.curated_for_you': 'Curated For You',
    'product.complementary_picks': 'Complementary Picks',
    'product.reservation_secured': 'Reservation Secured',
    'product.atelier_moment_booked': 'Your Riman Atelier moment is booked',
    'product.selection': 'Selection',
    'product.period_starts': 'Period Starts',
    'product.rental_policy': 'Rental Policy',
    'product.rental_policy_desc': '4-day hire, return on day five. Includes eco-friendly dry cleaning and couture insurance. Please ensure return within your window.',
    'product.security_deposit': 'Security Deposit',
    'product.continue_exploring': 'Continue Exploring',
    'product.go_to_checkout': 'Go to Checkout',
    'product.whatsapp': 'WhatsApp',
    'product.copy_link': 'Copy Link',
    'product.description_intro': 'Crafted from the finest',
    'product.description_mid': 'embodies the essence of modern luxury with its',
    'product.description_outro': 'design.',
    'product.toast_rental': 'Rental Booked',
    'product.toast_added': 'Added to Bag',
    'product.fitting_title': 'Sharjah Atelier Fitting',
    'product.fitting_desc': 'Rent with confidence. Book a 30-minute private fitting session to ensure your selected gown fits your silhouette perfectly before your rental date.',
    'product.texture_title': 'The Texture of Reverie',
    'product.texture_desc': 'Constructed with multi-layered silk organza for a weightless, infinite movement inspired by the dunes of Sharjah.',
    'product.rating': 'Rating',
    'product.enter_name': 'Enter your name',
    'product.share_experience': 'Share your experience...',
    'product.security_deposit_desc': 'A refundable deposit of',
    'product.will_be_held': 'will be held during the rental period.',
    'product.classic_view': 'Classic View',
    'product.view_3d': '3D Perspective',
    'product.silhouette': 'Silhouette',
    'product.color': 'Color',
    'product.care_instructions': 'Couture Care',
    'product.care_dry_clean': 'Professional Dry Clean',
    'product.care_dry_clean_desc': 'Expert cleaning by specialists trained in luxury garment care.',
    'product.care_store': 'Breathable Garment Bag',
    'product.care_store_desc': 'Store in a cool, dry place using the provided breathable garment bag.',
    'product.care_handle': 'Handle with Care',
    'product.care_handle_desc': 'Avoid direct contact with perfumes, cosmetics, and sharp accessories.',
    'product.care_steam': 'Professional Steaming',
    'product.care_steam_desc': 'Use low-heat steaming to remove wrinkles. Never iron directly on embellishments.',
    'product.ask_stylist': 'Ask a Stylist',
    'product.ask_stylist_desc': 'Book a complimentary consultation with our styling experts.',
    'product.select_size': 'Select Size',
    'product.cancel': 'Cancel',
    'product.quick_shop': 'Quick Shop',

    // Pricing
    'pricing.from': 'From',
    'pricing.rental_period': '3-day rental',
    'pricing.consultation_note': 'Final quote confirmed at your consultation — fitting and alterations included.',

    // Badges
    'badge.new': 'Majestic New',
    'badge.featured': 'Atelier Choice',
    'badge.gold': 'Pure Gold',
    'badge.3d': '3D View',

    // Collection page
    'collection.sort': 'Sort',
    'collection.sort_featured': 'featured',
    'collection.sort_newest': 'newest',
    'collection.sort_price_low': 'price low',
    'collection.sort_price_high': 'price high',
    'collection.colors': 'Colors',
    'collection.silhouette': 'Silhouette',
    'collection.year': 'Year',
    'collection.filters': 'Filters',
    'collection.all_silhouettes': 'All Silhouettes',
    'silhouette.A-Line': 'A-Line',
    'silhouette.Ballgown': 'Ball Gown',
    'silhouette.Mermaid': 'Mermaid',
    'silhouette.Column': 'Column / Sheath',
    'silhouette.Kaftan': 'Kaftan',
    'silhouette.One Size': 'Accessories',
    'collection.results': 'results',
    'collection.clear_all': 'Clear All',
    'collection.empty_heading': 'No designs found matching your filters.',
    'collection.empty_desc': 'Our collection is curated with intention. Try adjusting your filters or explore our full atelier.',
    'collection.view_all': 'View All Designs',

    // Search
    'search.placeholder': 'SEARCH THE ATELIER...',
    'search.results': 'Results',
    'search.advanced_filters': 'Advanced Filters',
    'search.empty_heading': 'No Precision Matches',
    'search.empty_desc': 'We could not find exactly what you were looking for. Please try a different search or contact our stylists for a bespoke request.',
    'search.clear': 'Clear All Selection',
    'search.recommended': 'You May Also Admire',

    // Wishlist
    'wishlist.title': 'Admiration List',
    'wishlist.subtitle': 'Designs that have captured your heart',
    'wishlist.empty': 'Your board is empty',
    'wishlist.empty_desc': 'Begin your journey by curating your favorite silhouettes.',
    'wishlist.explore': 'Explore Atelier',
    'wishlist.view': 'View',
    'wishlist.add_to_bag': 'Add to Bag',

    // Selection
    'selection.title': 'Your Selection',
    'selection.subtitle': 'Pieces kept aside for your private viewing',
    'selection.empty': 'Your selection is empty',
    'selection.empty_desc': 'Save the silhouettes that catch your eye — we will have them ready for your visit.',
    'selection.explore': 'Explore Atelier',
    'selection.view': 'View',
    'selection.add_to_bag': 'Add to Bag',
    'selection.request_viewing': 'Request Private Viewing',
    'selection.count': 'pieces selected',
    'selection.share': 'Share Selection',
    'selection.link_copied': 'Share link copied',
    'selection.shared_title': 'A Curated Selection',
    'selection.shared_subtitle': 'Pieces chosen for a private viewing at Atelier Riman',

    // Reviews
    'product.no_reviews_heading': 'No reflections yet',
    'product.no_reviews_desc': 'Be the first to share your experience',
    'product.add_photo': 'Add a photo',
    'product.upload_photo': 'Upload photo',
    'product.available': 'available',
    'product.fully_booked': 'fully booked',

    // Calendar
    'calendar.days': 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    'calendar.months': 'January,February,March,April,May,June,July,August,September,October,November,December',
    'calendar.available': 'Available',
    'calendar.booked': 'Booked',
    'calendar.prev': 'Previous month',
    'calendar.next': 'Next month',
    'calendar.nextAvailable': 'Next available date',
    'calendar.statusAvailable': 'available',
    'calendar.statusBooked': 'booked',
    'calendar.statusPast': 'past',
    'calendar.selectedPrefix': 'Selected:',
    'calendar.noAvailability': 'No availability in the next 6 months.',
    'calendar.fallbackNotice': "Availability couldn't be loaded — showing approximate data.",
    'calendar.retry': 'Retry',

    // Checkout extras
    'checkout.secured_stripe': 'Secured by Stripe',
    'checkout.secure_order_atelier': 'Secure Order — Payment at Atelier',
    'checkout.order_failed': 'Failed to place order. Please try again.',
    'checkout.country_default': 'United Arab Emirates',

    // Payment cancel
    'payment.cancel.title': 'Payment Cancelled',
    'payment.cancel.body': 'No charges were made. Your order has not been placed.',
    'payment.cancel.return_checkout': 'Return to Checkout',
    'payment.cancel.continue_browsing': 'Continue Browsing',

    // Wedding checklist
    'wedding.checklist.eyebrow': 'The Road to I Do',
    'wedding.checklist.title': 'Wedding Planning Checklist',
    'wedding.checklist.m12': '12 Months Before',
    'wedding.checklist.t12': 'Set your wedding date and venue.',
    'wedding.checklist.m11': '11 Months Before',
    'wedding.checklist.t11': 'Book your first Riman Atelier consultation.',
    'wedding.checklist.m9': '9 Months Before',
    'wedding.checklist.t9': 'Finalize your silhouette and fabric selection.',
    'wedding.checklist.m6': '6 Months Before',
    'wedding.checklist.t6': 'First fitting and embroidery details.',
    'wedding.checklist.m3': '3 Months Before',
    'wedding.checklist.t3': 'Accessorize with veils and headpieces.',
    'wedding.checklist.m1': '1 Month Before',
    'wedding.checklist.t1': 'Final fitting and secure collection.',

    // Wedding timeline
    'wedding.timeline.title': 'Wedding Timeline',
    'wedding.timeline.subtitle': 'Planning your journey to I DO',
    'wedding.timeline.return_home': 'Return Home',

    // Newsletter modal
    'newsletter.title': 'The Atelier Circle',
    'newsletter.body': 'Join for exclusive previews of our new bridal collections and private viewings in Sharjah.',
    'newsletter.email_placeholder': 'E-mail Address',
    'newsletter.email_aria': 'Email address',
    'newsletter.cta': 'Join The Society',

    // Cookie banner
    'cookies.heading': 'Privacy & Elegance',
    'cookies.body': 'We use cookies to curate a personalized atelier experience.',
    'cookies.learn': 'Learn details',
    'cookies.accept': 'Accept & Explore',
    'cookies.reject': 'Reject',

    // Errors & common
    'errors.tech_title': 'A Technical Moment',
    'errors.tech_body': 'Our digital atelier is experiencing a brief pause. Please refresh the page or return to our home collection.',
    'errors.return_atelier': 'Return to Atelier',
    'common.close': 'Close',
    'common.retry': 'Retry',
    'threed.initializing': 'Initializing 3D Detail',

    // Toasts & fallbacks
    'product.toast_suffix_rental': 'rental booked',
    'product.toast_suffix_added': 'added to your collection',
    'product.fabric_default': 'Luxury Blend',
    'auth.profile_missing_title': 'Profile not found',
    'auth.load_fail_title': 'Could not load account',
    'auth.limited_msg': 'Some features may be limited.',
    'threed.unavailable': '3D viewer unavailable',
    'threed.reset_view': 'Reset View',
    'common.whatsapp_label': 'Chat with us on WhatsApp',
    'wishlist.remove_aria': 'Remove from selection',

    // Checkout
    'checkout.empty': 'Your Bag is Empty',
    'checkout.empty_desc': 'Please select pieces from our collection first.',
    'checkout.explore': 'Explore Collection',
    'checkout.step_identity': 'Identity',
    'checkout.step_logistics': 'Logistics',
    'checkout.step_confirm': 'Confirm',
    'checkout.personal_details': 'Personal Details',
    'checkout.delivery_info': 'Delivery Information',
    'checkout.review': 'Review & Confirm',
    'checkout.first_name': 'First Name',
    'checkout.last_name': 'Last Name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone Number',
    'checkout.address': 'Street Address',
    'checkout.city': 'City',
    'checkout.country': 'Country',
    'checkout.continue_logistics': 'Continue to Logistics',
    'checkout.review_order': 'Review Order',
    'checkout.previous': 'Previous',
    'checkout.your_details': 'Your Details',
    'checkout.your_selections': 'Your Selections',
    'checkout.subtotal': 'Subtotal',
    'checkout.delivery': 'Atelier Delivery',
    'checkout.complimentary': 'Complimentary',
    'checkout.vat': 'V.A.T (5%)',
    'checkout.included': 'Included',
    'checkout.total': 'Total',
    'checkout.bag_summary': 'Bag Summary',
    'checkout.order_notes': 'Order Notes (Optional)',
    'checkout.notes_placeholder': 'Any special requests or measurements...',
    'checkout.payment_method': 'Payment Method',
    'checkout.pay_atelier': 'Reserve at Atelier',
    'checkout.pay_atelier_desc': 'No online payment — owner confirms every order via WhatsApp. Worldwide delivery.',
    'checkout.pay_online': 'Pay Online',
    'checkout.pay_online_desc': 'Secure card payment via Stripe — Visa & Mastercard accepted. Worldwide delivery.',
    'checkout.secure_online': 'Secure Online Payment — Visa / Mastercard',
    'checkout.secure_online_desc': 'Your card will be charged the full amount via Stripe. Our owner then confirms fitting and worldwide delivery.',
    'checkout.instore_payment': 'Reservation & Owner Confirmation',
    'checkout.instore_desc': 'Our owner confirms every order via WhatsApp within 24 hours. Payment on collection or delivery. We deliver worldwide.',
    'checkout.confirm_order': 'Confirm Order',
    'checkout.order_received': 'Order Received',
    'checkout.order_preparing': 'Your investment is being prepared at our atelier.',
    'checkout.confirmation_email': 'Confirmation will be sent to',
    'checkout.contact_24h': 'Our team will contact you within 24 hours to arrange fitting, delivery, and payment details.',
    'checkout.view_dashboard': 'View My Dashboard',
    'checkout.required': 'Required',
    'checkout.size': 'Size',
    'checkout.date': 'Date',
    'checkout.qty': 'Qty',
    'checkout.secure_payment': 'Secure Payment',
    'checkout.returns_policy': '14-Day Returns',
    'checkout.whatsapp_support': 'WhatsApp Support',
    'checkout.order_summary': 'Order Summary',
    'checkout.show_summary': 'Show Order Summary',
    'checkout.hide_summary': 'Hide Order Summary',
    'checkout.items_count': '{count} items',
    'checkout.back_to_shop': 'Back to Shop',
    'checkout.val_email': 'Please enter a valid email address',
    'checkout.val_phone': 'Please enter a valid phone number',
    'checkout.val_name': 'Please enter your name',
    'checkout.val_address': 'Please enter your street address',
    'checkout.val_city': 'Please enter your city',
    'checkout.val_country': 'Please select your country',
    'checkout.name_label': 'Name',

    // Payment
    'payment.verifying': 'Verifying Payment',
    'payment.please_wait': 'Please wait a moment...',
    'payment.success_title': 'Payment Successful',
    'payment.success_sub': 'Your investment has been received.',
    'payment.sent_to': 'Confirmation sent to',
    'payment.success_body': 'Our team will contact you within 24 hours to arrange fitting and delivery details.',
    'payment.dashboard': 'View My Dashboard',
    'payment.error_title': 'Payment Not Verified',
    'payment.error_body': 'Please contact our atelier to confirm your order.',
    'payment.contact': 'Contact Us',
    'payment.home': 'Return Home',

    // Auth
    'auth.signin': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.welcome_back': 'Welcome back to the Atelier',
    'auth.join': 'Join the Riman Society',
    'auth.enter_atelier': 'Enter Atelier',
    'auth.create_profile': 'Create Profile',
    'auth.authenticated': 'Authenticated',
    'auth.redirecting': 'Redirecting to your profile...',
    'auth.full_name': 'Full Name',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.name_placeholder': 'E.g. Sarah Mansour',
    'auth.email_placeholder': 'name@example.com',
    'auth.password_placeholder': 'Minimum 6 characters',
    'auth.no_account': "Don't have an account? Create one",
    'auth.has_account': 'Already have an account? Sign in',
    'auth.clear_session': 'Trouble connecting? Clear Session',
    'auth.error_email': 'Please enter your email address.',
    'auth.error_password': 'Password must be at least 6 characters.',
    'auth.error_name': 'Please enter your name.',

    // Appointment
    'appointment.heading': 'Private Consultation',
    'appointment.desc': 'Experience the Riman atelier in person. Our master stylists will guide you through our collection and help you find the dress of your dreams.',
    'appointment.step_details': 'Details',
    'appointment.step_schedule': 'Schedule',
    'appointment.step_confirm': 'Confirm',
    'appointment.your_details': 'Your Details',
    'appointment.choose_datetime': 'Choose Date & Time',
    'appointment.review_confirm': 'Review & Confirm',
    'appointment.full_name': 'Full Name *',
    'appointment.email': 'Email Address *',
    'appointment.phone': 'Phone Number *',
    'appointment.service_type': 'Service Type *',
    'appointment.select_service': 'Select a service',
    'appointment.your_gowns': 'Your Selected Pieces',
    'appointment.select_date': 'Select Date *',
    'appointment.select_time': 'Select Time *',
    'appointment.special_requests': 'Special Requests (Optional)',
    'appointment.notes_placeholder': 'Anything specific you\'d like us to prepare for your visit...',
    'appointment.continue_scheduling': 'Continue to Scheduling',
    'appointment.review_booking': 'Review Booking',
    'appointment.confirm_booking': 'Confirm Booking',
    'appointment.confirming': 'Confirming...',
    'appointment.back': 'Back',
    'appointment.name': 'Name',
    'appointment.email_label': 'Email',
    'appointment.phone_label': 'Phone',
    'appointment.service_label': 'Service',
    'appointment.date_label': 'Date',
    'appointment.time_label': 'Time',
    'appointment.booked': 'Booking Confirmed',
    'appointment.thank_you': 'Thank you',
    'appointment.appointment_booked_for': 'appointment is booked for',
    'appointment.at': 'at',
    'appointment.confirmation_sent': 'A confirmation will be sent to',
    'appointment.our_team_reach': 'Our team will reach out to confirm details.',
    'appointment.explore_collection': 'Explore Collection',
    'appointment.whatsapp_continue': 'Continue on WhatsApp',
    'appointment.error_name': 'Please enter your name',
    'appointment.error_email': 'Please enter a valid email',
    'appointment.error_phone': 'Please enter your phone number',
    'appointment.error_service': 'Please select a service type',
    'appointment.error_date': 'Please select a date',
    'appointment.error_time': 'Please select a time',
    'appointment.fill_all': 'Please fill in all required fields',
    'appointment.select_date_time': 'Please select a date and time',
    'appointment.something_wrong': 'Something went wrong. Please try again or contact us directly via WhatsApp.',
    'appointment.atelier_hours': 'Daily: 11AM – 9PM  |  Friday: after prayer – 9PM',
    'appointment.whatsapp_help': 'Need help? Chat on WhatsApp',

    // Footer
    'footer.about': "Crafting Sharjah's most exquisite gowns. Reimagining the heritage of elegance for the modern muse, where every thread carries a story of royal intent.",
    'footer.location': 'Al Zahra St, Sharjah, UAE',
    'footer.ascend': 'Ascend to Top',
    'footer.rights': 'Crafted in Sharjah.',
    'footer.privacy': 'Privacy',
    'footer.legal': 'Legal',
    'footer.newsletter_title': 'The Atelier Letter',
    'footer.newsletter_text': 'Join our Inner Circle for exclusive collection previews and couture insights.',
    'footer.newsletter_placeholder': 'Your Email Address',
    'footer.submitted': 'SUBMITTED',
    'footer.collections': 'Collections',
    'footer.services': 'Services',
    'footer.atelier_location': 'Atelier Location',
    'footer.consultation': 'Private Consultation',
    'footer.links': 'Quick Links',
    'footer.follow': 'Follow Us',
    'footer.newsletter': 'Newsletter',
    'footer.bespoke_fitting': 'Bespoke Fitting',
    'footer.aura_consultation': 'Aura Consultation',
    'footer.bridal_concierge': 'Bridal Concierge',
    'footer.assistance': 'Assistance',

    // Forms
    'form.name': 'Full Name',
    'form.email': 'Email Address',
    'form.message': 'Message',
    'form.submit': 'Send Inquiry',

    // Profile
    'profile.dashboard': 'Heritage Dashboard',
    'profile.welcome': 'Welcome back to the Riman Society',
    'profile.member': 'Member',
    'profile.total_investments': 'Total Investments',
    'profile.active_rentals': 'Active Rentals',
    'profile.orders_placed': 'Orders Placed',
    'profile.recent_engagements': 'Recent Engagements',
    'profile.orders': 'Orders & Rentals',
    'profile.appointments': 'Appointments',
    'profile.preferences': 'Preferences',
    'profile.sign_out': 'Sign Out',
    'profile.no_orders': 'No orders yet. Begin your atelier journey.',
    'profile.backend_not_connected': 'Backend not connected. Order history unavailable.',
    'profile.rental_booking': 'Rental Booking',
    'profile.combined_order': 'Combined Order',
    'profile.purchase_order': 'Purchase',
    'profile.explore_new': 'Explore New Collections',

    // Alterations
    'alt.hero_title': 'The Art of Bespoke Fitting',
    'alt.hero_desc': "A gown is only as beautiful as its fit. Our master tailors in Sharjah specialize in perfecting the world's most intricate silhouettes.",
    'alt.book_fitting': 'Book Your Fitting',
    'alt.step1_title': 'Initial Consultation',
    'alt.step1_desc': 'A private 45-minute session to assess the silhouette and discuss your vision.',
    'alt.step2_title': 'Pinning & Sculpting',
    'alt.step2_desc': 'Our head tailor personally pins the garment to ensure a second-skin fit.',
    'alt.step3_title': 'Detail Refinement',
    'alt.step3_desc': 'Hand-finishing hems, re-beading areas, and reinforcing structural boning.',
    'alt.step4_title': 'Final Reveal',
    'alt.step4_desc': 'The conclusive fitting to ensure comfort, mobility, and perfection.',
    'alt.service_bridal_title': 'Bridal Perfection',
    'alt.service_bridal_desc': 'Exclusively for Riman brides and external couture gowns. Complex bustier adjustments and multi-layered hem shortening.',
    'alt.service_evening_title': 'Evening Reconstruction',
    'alt.service_evening_desc': "Transforming off-the-rack luxury into custom-fit masterpieces. Neckline modifications and sleeve additions.",
    'alt.service_urgent_title': 'Urgent Refinement',
    'alt.service_urgent_desc': 'Last-minute adjustments for galas and events. Subject to availability at our Sharjah atelier.',
    'alt.fitting_journey': 'The Fitting Journey',
    'alt.cta_heading': 'Does your gown deserve better?',
    'alt.cta_desc': "We accept a limited number of external alterations each month to maintain our quality standards. Whether it's a family heirloom or a recent acquisition, we treat every thread with the respect it deserves.",
    'alt.available': 'Available Mon-Thu',
    'alt.guarantee': '3 Fitting Guarantee',
    'alt.inquire': 'Inquire About Availability',

    // Quiz
    'quiz.q1': 'Where do you envision your celebration?',
    'quiz.q1_opt1': 'Grand Ballroom in Sharjah',
    'quiz.q1_opt2': 'Desert Oasis under the Stars',
    'quiz.q1_opt3': 'Private Coastal Villa',
    'quiz.q1_opt4': 'Modern Skyline Terrace',
    'quiz.q2': 'Which silhouette speaks to your soul?',
    'quiz.q2_opt1': 'Majestic Ballgown',
    'quiz.q2_opt2': 'Sophisticated Mermaid',
    'quiz.q2_opt3': 'Ethereal A-Line',
    'quiz.q2_opt4': 'Modern Slip Dress',
    'quiz.q3': 'Which texture feels most like you?',
    'quiz.q3_opt1': 'Intricate Hand-Stitched Lace',
    'quiz.q3_opt2': 'Architectural Silk Mikado',
    'quiz.q3_opt3': 'Flowing Chiffon & Tulle',
    'quiz.q3_opt4': 'Luminous Satin & Pearls',
    'quiz.q4': "What is the defining 'aura' of your day?",
    'quiz.q4_opt1': 'Timeless Heritage',
    'quiz.q4_opt2': 'Bold Avant-Garde',
    'quiz.q4_opt3': 'Soft Romanticism',
    'quiz.q4_opt4': 'Understated Minimalism',
    'quiz.error': 'Our stylists are currently busy. Please try again or visit us in person.',
    'quiz.title': 'The Style Registry',
    'quiz.subtitle': 'Discover your Riman Aura',
    'quiz.loading': 'Consulting with our virtual master tailors...',
    'quiz.your_aesthetic': 'Your Aesthetic',
    'quiz.stylist_tip': "Stylist's Tip",
    'quiz.view_recs': 'View Recommendations',
    'quiz.retry': 'Re-Experience',
    'quiz.try_again': 'Try Again',
    'quiz.progress': 'Question',
    'quiz.your_matches': 'Your Perfect Matches',
    'quiz.no_matches': 'Let Us Help You Find The One',
    'quiz.based_on_answers': 'Based on your answers, we think you will love these designs.',
    'quiz.browse_collection': 'Browse our curated collection to find your perfect piece.',
    'quiz.try_different': 'Try different options to discover more styles.',
    'quiz.view_all': 'View Full Collection',

    // FAQ
    'faq.category_rental': 'Rental Services',
    'faq.q_rental_1': 'How long is the standard rental period?',
    'faq.a_rental_1': "Our standard 'Premier Hire' period is 7 days. Extensions can be arranged for an additional fee, subject to availability. We recommend booking at least 4 weeks in advance for your desired dates.",
    'faq.q_rental_2': 'Is dry cleaning included in the rental price?',
    'faq.a_rental_2': 'Yes, every Riman rental includes professional eco-friendly dry cleaning both before and after your event. We handle all garment care so you can focus on your celebration.',
    'faq.q_rental_3': 'What happens if I accidentally damage a rental?',
    'faq.a_rental_3': "All rentals include basic 'Couture Insurance' covering minor mishaps. For significant damage, a deduction from your security deposit may apply. We'll always discuss this transparently with you.",
    'faq.category_bespoke': 'Bespoke & Alterations',
    'faq.q_bespoke_1': 'Do I need an appointment for a fitting?',
    'faq.a_bespoke_1': 'Yes, all fittings at our Sharjah atelier are strictly by appointment to ensure you receive our full attention. You can book online or call us directly.',
    'faq.q_bespoke_2': 'Can you alter gowns not purchased at Riman?',
    'faq.a_bespoke_2': 'We do accept a limited number of external alterations each month. Our team will assess your gown during an initial consultation to ensure we can achieve the result you desire.',
    'faq.category_shipping': 'Shipping & Returns',
    'faq.q_shipping_1': 'Do you ship internationally?',
    'faq.a_shipping_1': 'Yes, we ship across the UAE and GCC. International shipping for purchased items is available upon request. Rental items are available for in-atelier pickup or delivery within the UAE only.',
    'faq.q_shipping_2': 'What is your return policy for purchases?',
    'faq.a_shipping_2': 'We offer a 14-day return policy for unworn, original-condition items with tags attached. Bespoke and customized items are final sale. Please contact our concierge for return authorization.',
    'faq.search_placeholder': 'How can we assist you today?',
    'faq.still_unsure': 'Still Unsure?',
    'faq.still_unsure_desc': 'Our atelier concierge is available 9 AM - 9 PM GST for immediate assistance.',
    'faq.submit_inquiry': 'Submit Inquiry',
    'faq.whatsapp_expert': 'WhatsApp Expert',
    'faq.title': 'Service Concierge',

    // Size Guide
    'size_guide.title': 'Size Guide',
    'size_guide.desc': 'All measurements are in centimeters (cm). For the best fit, we recommend having a professional take your measurements.',
    'size_guide.size': 'Size',
    'size_guide.bust': 'Bust',
    'size_guide.waist': 'Waist',
    'size_guide.hips': 'Hips',
    'size_guide.cm': 'cm',
    'size_guide.how_to_measure': 'How to Measure',
    'size_guide.measure_bust': 'Bust:',
    'size_guide.measure_bust_desc': 'Measure around the fullest part of your chest.',
    'size_guide.measure_waist': 'Waist:',
    'size_guide.measure_waist_desc': 'Measure around the narrowest part of your natural waistline.',
    'size_guide.measure_hips': 'Hips:',
    'size_guide.measure_hips_desc': 'Measure around the fullest part of your hips.',
    'size_guide.alterations_title': 'Bespoke Alterations:',
    'size_guide.alterations_desc': 'Every Riman purchase includes complimentary alterations at our Sharjah atelier. Our master tailors will ensure your garment fits perfectly.',

    // About — narratives, quote, roles, stats
    'about.narrative_1': "Founded in the heart of Sharjah, Riman Fashion was born from a passion for preserving traditional artistry while embracing contemporary design. Our atelier is the zenith of luxury, where every thread is woven with royal intent.",
    'about.narrative_2': "Today, we stand as a premier destination for those seeking more than just a gown. Every piece in our collection is a testament to sleepless nights at the sewing table, sourced Italian silks, and the delicate art of French lace application.",
    'about.quote': "We don't just sell dresses; we curate the moments that will be whispered about for generations.",
    'about.quote_author': '— Sarah Mansour, Founder',
    'about.pillars': 'The Atelier Pillars',
    'about.visionaries': 'The Visionaries',
    'about.collective': 'The Riman Collective',
    'about.role_founder': 'Founder & Chief Designer',
    'about.role_embroidery': 'Head of Embroidery',
    'about.role_jewelry': 'Gilded Jewelry Lead',
    'about.stat_beads': 'Hand-applied beads per gown',
    'about.stat_runways': 'Global runways graced',

    // Instagram
    'instagram.title': 'The Riman Aura',
    'instagram.follow': 'Follow us @rimanfashion',
    'instagram.view_aura': 'View Aura',
    'instagram.explore': 'Explore Full Gallery',

    // Contact
    'contact.narrative': "We invite you to experience our collections in person. Our Sharjah atelier offers a private, serene environment for you to explore your bridal vision and our Fine Jewelry pieces.",
    'contact.location': 'Location',
    'contact.location_addr': 'Al Zahra St, Sharjah, United Arab Emirates',
    'contact.contact_details': 'Contact Details',
    'contact.phone_email': 'Phone: +971 553 730 792 | Email: boutique@riman.ae',
    'contact.hours': 'Opening Hours',
    'contact.hours_detail': 'Daily: 11:00 AM - 9:00 PM | Friday: after prayer - 9:00 PM',
    'contact.special_note': 'Special Note',
    'contact.special_note_desc': 'Friday visits open after prayer. Every booking is confirmed by the atelier owner via WhatsApp.',
    'contact.request_consultation': 'Request Consultation',
    'contact.inquiry_type': 'Inquiry Type',
    'contact.bridal_consultation': 'Bridal Consultation',
    'contact.evening_inquiry': 'Evening Wear Inquiry',
    'contact.rental_booking': 'Rental Booking',
    'contact.bespoke_alterations': 'Bespoke Alterations',
    'contact.vision_prefs': 'Vision & Preferences',
    'contact.vision_placeholder': 'Tell us about your event, preferred collection, or silhouette...',
    'contact.success_title': 'Request Sent Successfully',
    'contact.success_desc': 'Our team will respond within 24 hours.',
    'contact.write_another': 'Write Another Request',
    'contact.val_name': 'Name must be at least 2 characters',
    'contact.val_email': 'Invalid email address',
    'contact.val_phone': 'Valid phone number required',
    'contact.val_details': 'Please provide more details about your inquiry',
    'contact.toast_demo_title': 'Demo Mode',
    'contact.toast_demo_msg': 'This form is not connected to a backend. Your message was not saved.',
    'contact.toast_sent_title': 'Request Sent',
    'contact.toast_sent_msg': 'Our team will respond within 24 hours.',

    // Header
    'header.collections': 'Collections',
    'header.atelier': 'Atelier',
    'header.services': 'Services',
    'header.tagline': 'Sharjah, UAE | Premier Bridal Atelier',
    'header.menu_open': 'Open navigation menu',
    'header.menu_close': 'Close menu',
    'header.switch_to_ar': 'Switch to Arabic',
    'header.switch_to_en': 'Switch to English',
    'header.search': 'Search',
    'header.style_quiz': 'Style Quiz',
    'header.your_selection': 'Your Selection',
    'header.account': 'Account',
    'header.bag': 'Shopping Bag',
    'notfound.title': 'Beyond Our Collection',
    'notfound.desc': 'The page you are looking for does not exist or has been moved to a new location within our atelier.',
    'notfound.home': 'Return Home',
    'notfound.browse': 'Browse Collection',
    'notfound.contact': 'Contact Atelier',
    'footer.newsletter_submit': 'Subscribe to newsletter',

    // Footer
    'footer.fine_jewelry': 'Fine Jewelry',
    'footer.valid_email': 'Please enter a valid email',

    // Gallery
    'gallery.title': 'Visual Reverie',
    'gallery.subtitle': 'Atelier Gallery',
    'gallery.description': 'A curated collection of our finest moments',
    'gallery.filter_all': 'All',
    'gallery.filter_bridal': 'Bridal',
    'gallery.filter_evening': 'Evening',
    'gallery.filter_jewelry': 'Jewelry',
    'gallery.filter_bts': 'Behind the Scenes',
    'gallery.filter_clients': 'Client Stories',
    'gallery.load_more': 'Load More',
    'gallery.view_full': 'View Full Gallery',
    'gallery.back': 'Back to Gallery',
    'gallery.no_items': 'No items found in this category',
    'gallery.admin_title': 'Gallery Management',
    'gallery.admin_upload': 'Upload Media',
    'gallery.admin_edit': 'Edit Item',
    'gallery.admin_delete': 'Delete Item',
    'gallery.admin_featured': 'Featured',
    'gallery.admin_sort': 'Sort Order',
  },

  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.bridal': 'فساتين الزفاف',
    'nav.evening': 'فساتين السهرة',
    'nav.rentals': 'الإيجار',
    'nav.about': 'قصتنا',
    'nav.contact': 'تواصل معنا',
    'nav.timeline': 'الجدول الزمني',
    'nav.style_quiz': 'اختبار الأناقة',
    'nav.jewelry': 'المجوهرات الراقية',
    'nav.accessories': 'الإكسسوارات',
    'nav.gallery': 'المعرض',
    'nav.alterations': 'التعديلات',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.appointment': 'زيارة خاصة',

    // Categories
    'cat.bridal': 'العرائس',
    'cat.evening': 'السهرة',
    'cat.rentals': 'الإيجار',
    'cat.jewelry': 'المجوهرات الراقية',
    'cat.collection': 'المجموعة',
    'cat.gala': 'فساتين الحفلات',
    'cat.service': 'خدمة مميزة',
    'cat.majestic': 'تشكيلة مهيبة',
    'cat.all': 'جميع التصاميم',
    'cat.bridal_title': 'مجموعة العرائس',
    'cat.evening_title': 'فساتين السهرة',
    'cat.rental_title': 'الإيجار المتميز',
    'cat.jewelry_title': 'المجوهرات المهيبة',
    'cat.accessories_title': 'الإكسسوارات',
    'cat.subtitle': 'تصاميم راقية وأقمشة فاخرة مختارة بعناية للمرأة العصرية الواعية.',

    // Hero
    'hero.title': 'حلمٌ وجوهر',
    'hero.subtitle': 'دار الأزياء الرائدة في الشارقة',
    'hero.discover': 'اكتشف',

    // Salon chapters
    'chapter.atelier': 'الأتيليه',
    'chapter.silhouettes': 'القصات',
    'chapter.savoir_faire': 'الحرفية',
    'invitation.line': 'أكمِل الحوار — اطلب زيارة خاصة.',
    'invitation.cta': 'اطلب زيارة خاصة',
    'nav.private_viewing': 'زيارة خاصة',
    'silhouettes.look': 'إطلالة',
    'silhouettes.enquire': 'استفسار',

    // Salon homepage
    'atelier.heading': 'إتقان أيقونة الإرث',
    'atelier.quote': 'يبدأ كل شيء بتوترٍ جميل — هندسة حرير الميكادو في مواجهة همس التول الفرنسي.',
    'atelier.body': 'من مرسمنا في الشارقة، نقطع باليد، ونقاس بالنظر، ونُنهي العمل بالصبر. فساتين أقل، وإتقانًا أكبر.',
    'savoir.p1': 'نقلّ القليل لنُتقن أكثر. نُشكّل الحرير الميكادو والتول الفرنسي يدويًا، تاركين للقماش أن يرسم الخط.',
    'savoir.p2': 'كل تخصصات الدار — الزفاف، السهرة، الإيجار — تبدأ من الطاولة نفسها: قماش، خيط، وصبر.',
    'disciplines.bridal': 'فساتين تُخلَّد لِيومٍ واحد، وتبقى للأبد.',
    'disciplines.evening': 'حضور سجادة حمراء، مفصّل للحظة.',
    'disciplines.rentals': 'كوتور ليلة واحدة، يبقى بلا عيب.',
    'disciplines.discover': 'اكتشف',
    'invitation.heading': 'عِش لمسة ريمان',
    'invitation.contact_line': 'الشارقة · بموعد مسبق فقط',

    // Couture Motion — Philosophy & Lookbook
    'philosophy.eyebrow': 'الفلسفة',
    'philosophy.statement': 'كل فستان يبدأ كهمسة — رسم، قماش، حلم. حرفيو دارنا يقصّون أقل، ويقصّون أفضل.',
    'philosophy.stat_years': 'سنوات من الحرفية',
    'philosophy.stat_fibres': 'ألياف طبيعية',
    'philosophy.stat_brides': 'عرائس بأزياء مخصصة',
    'lookbook.eyebrow': 'دفتر الإطلالات',
    'lookbook.heading': 'قصّات في حركة',
    'lookbook.cta': 'شاهدي المجموعة',

    // CTAs
    'cta.explore': 'استكشف المجموعة',
    'cta.viewing': 'اطلب عرضاً خاصاً',
    'cta.appointment': 'احجز موعداً',
    'cta.view_all': 'عرض الكل',
    'cta.discover_all': 'اكتشف الكل',

    // Heritage section
    'heritage.title': 'تراثنا',
    'heritage.heading': 'إرث ريمان',

    // Curated / Featured
    'curated.eyebrow': 'ذوق منتقى',
    'curated.heading': 'تصاميم مميزة',

    // Featured In
    'featured_in.title': 'كما ورد في',
    'featured_in.trusted': 'موثوق بها من قبل أبرز مطبوعات الموضة العالمية',

    // Jewelry section
    'jewelry.eyebrow': 'مجوهرات ريمان الراقية',
    'jewelry.heading': 'مجموعة الذهب المصنوعة حسب الطلب',

    // Experience / Consultation banner
    'experience.heading': 'اختبر لمسة ريمان',
    'experience.desc': 'احجز استشارة خاصة مجانية في دارنا بالشارقة. سيقودك كبار المصممين عبر مجموعتنا ويساعدونك في العثور على فستان أحلامك.',
    'experience.cta': 'احضر عرضك الخاص',
    'experience.bridal': 'أزياء العرائس',
    'experience.evening': 'أزياء السهرة',
    'experience.jewelry': 'المجوهرات الراقية',

    // About
    'about.title': 'إرث ريمان',
    'about.hero_subtitle': 'تأسس عام ٢٠١٢ — الشارقة، الإمارات',
    'about.hero_title': 'تراث ريمان',
    'about.pillar_1_title': 'حرفية مسؤولة',
    'about.pillar_1_desc': 'نتعاون حصراً مع موردي الحرير التجارة العادلة وكبار الحرفيين.',
    'about.pillar_2_title': 'روابط التراث',
    'about.pillar_2_desc': 'متجذرون بعمق في الثقافة الإماراتية باستخدام تقنيات تقليدية مثل التلي.',
    'about.pillar_3_title': 'خدمة مدى الحياة',
    'about.pillar_3_desc': 'رعاية دائمة لاستثماراتك من ريمان.',
    'about.pillars_heading': 'أركان الدار',
    'about.team_eyebrow': 'أصحاب الرؤية',
    'about.team_heading': 'فريق ريمان',

    // Terms
    'terms.title': 'شروط الخدمة',
    'terms.subtitle': 'سياسات المتجر',
    'terms.last_updated': 'آخر تحديث: ٢٨ يوليو ٢٠٢٦',
    'terms.section_1_title': '١. مقدمة',
    'terms.section_1_body': 'مرحباً بكم في أتيليه ريمان. تحكم شروط الخدمة هذه استخدامكم لموقعنا وخدماتنا. بالتصفح أو الشراء من موقعنا، أنتم توافقون على الالتزام بهذه الشروط. إذا كنتم لا توافقون، فيرجى عدم استخدام خدماتنا.',
    'terms.section_2_title': '٢. الحساب والتسجيل',
    'terms.section_2_body': 'عند إنشاء حساب، يجب عليكم تقديم معلومات دقيقة وكاملة. أنتم مسؤولون عن الحفاظ على سرية بيانات الدخول الخاصة بكم وعن جميع الأنشطة التي تتم تحت حسابكم. نحتفظ بالحق في تعليق أو إنهاء الحسابات المخالفة لهذه الشروط.',
    'terms.section_3_title': '٣. المنتجات والأسعار',
    'terms.section_3_body': 'جميع الأسعار مدروجة بالدرهم الإماراتي ما لم يذكر خلاف ذلك. نسعى للدقة ولكن لا نضمن خلو صور أو أوصاف المنتجات من الأخطاء. نحتفظ بالحق في تصحيح الأخطاء أو تعديل الأسعار أو إيقاف المنتجات دون إشعار مسبق.',
    'terms.section_4_title': '٤. الطلبات والدفع',
    'terms.section_4_body': 'تتم معالجة الطلبات عبر سترايب، معالج دفع آمن تابع لجهة خارجية. بتقديم طلب، أنتم تفوضوننا بخصم المبلغ المستحق. نحتفظ بالحق في رفض أو إلغاء الطلبات حسب تقديرنا.',
    'terms.section_5_title': '٥. الشحن والتوصيل',
    'terms.section_5_body': 'نقوم بالشحن داخل الإمارات وإلى وجهات دولية محددة. أوقات التوصيل تقديرية وغير مضمونة. ينتقل خطر الفقدان إليكم عند التسليم. القطع المخصصة أو المصنوعة حسب الطلب قد تتطلب فترات إنتاج أطول.',
    'terms.section_6_title': '٦. الإرجاع والاستبدال والتأجير',
    'terms.section_6_body': 'يمكن إرجاع المشتريات خلال ١٤ يوماً من التسليم بحالتها الأصلية. تخضع قطع التأجير لاتفاقية تأجير منفصلة تتضمن شروط الإيداع والمدة والضرر. التعديلات نهائية وغير قابلة للإرجاع إلا في حالة العيوب.',
    'terms.section_7_title': '٧. الملكية الفكرية',
    'terms.section_7_body': 'جميع محتويات هذا الموقع — بما في ذلك التصاميم والصور والشعارات والنصوص والرسومات — هي ملكية حصرية لأتيليه ريمان ومحمية بموجب قوانين حقوق النشر الإماراتية والدولية. لا يجوز إعادة إنتاج أو توزيع أو تعديل أي محتوى دون موافقتنا الكتابية.',
    'terms.section_8_title': '٨. تحديد المسؤولية',
    'terms.section_8_body': 'أتيليه ريمان غير مسؤول عن الأضرار غير المباشرة أو العرضية أو التبعية الناشئة عن استخدام موقعنا أو منتجاتنا. تقتصر مسؤوليتنا الإجمالية على المبلغ الذي دفعته مقابل المنتج المعني.',
    'terms.section_9_title': '٩. القانون الحاكم',
    'terms.section_9_body': 'تخضع هذه الشروط لقوانين دولة الإمارات العربية المتحدة، إمارة الشارقة. يتم حل النزاعات عبر التفاوض الودي أو، عند فشله، في محاكم الشارقة.',
    'terms.contact_title': 'اتصل بنا',
    'terms.contact_body': 'للاستفسارات حول هذه الشروط، يرجى التواصل مع فريقنا:',
    'terms.contact_info': 'أتيليه ريمان — شارع الزهرة، الشارقة، الإمارات — hello@riman.ae',

    // Privacy
    'privacy.title': 'سياسة الخصوصية',
    'privacy.subtitle': 'أمن بياناتكم',
    'privacy.last_updated': 'آخر تحديث: ٢٨ يوليو ٢٠٢٦',
    'privacy.section_1_title': '١. المعلومات التي نجمعها',
    'privacy.section_1_body': 'نحن نجمع المعلومات الشخصية التي تقدمونها عند تقديم طلب أو إنشاء حساب أو التواصل معنا — بما في ذلك الاسم والبريد الإلكتروني ورقم الهاتف وعنوان الشحن وتفاصيل الدفع. كما نجمع بيانات التصفح مثل الصفحات التي تمت زيارتها ومعلومات الجهاز.',
    'privacy.section_2_title': '٢. كيفية استخدام معلوماتكم',
    'privacy.section_2_body': 'نستخدم بياناتكم لمعالجة الطلبات والتواصل بشأن حالة الطلب وإرسال رسائل متعلقة بالخدمة وتحسين موقعنا والامتثال للالتزامات القانونية. نحن لا نبيع معلوماتكم الشخصية لأطراف ثالثة.',
    'privacy.section_3_title': '٣. معالجة المدفوعات',
    'privacy.section_3_body': 'تتم جميع المدفوعات عبر سترايب، معالج دفع متوافق مع معايير PCI-DSS. لا نخزن أرقام بطاقات الائتمان الكاملة على خوادمنا. تتلقى سترايب بيانات الدفع الخاصة بكم مباشرة وتعالجها وفقاً لسياسة الخصوصية الخاصة بها.',
    'privacy.section_4_title': '٤. مشاركة البيانات',
    'privacy.section_4_body': 'قد نشارك معلوماتكم مع أطراف ثالثة موثوقة تساعدنا في تشغيل أعمالنا — بما في ذلك شركات الشحن ومعالجي الدفع ومقدمي خدمات تكنولوجيا المعلومات. هذه الأطراف ملزمة تعاقدياً بحماية بياناتكم.',
    'privacy.section_5_title': '٥. ملفات تعريف الارتباط',
    'privacy.section_5_body': 'يستخدم موقعنا ملفات تعريف الارتباط الأساسية للوظائف. كما نستخدم ملفات تحليلات (Fathom، Plausible) لفهم حركة المرور دون تتبع المستخدمين بشكل فردي. يمكنكم التحكم في تفضيلات ملفات تعريف الارتباط من خلال إعدادات المتصفح.',
    'privacy.section_6_title': '٦. حقوقكم',
    'privacy.section_6_body': 'لديكم الحق في الوصول إلى بياناتكم الشخصية المحفوظة لدينا أو تصحيحها أو حذفها. كما يحق لكم الاعتراض على أو تقييد بعض المعالجة. لممارسة هذه الحقوق، اتصلوا بنا على العنوان أدناه. سنرد خلال ٣٠ يوماً.',
    'privacy.section_7_title': '٧. أمن البيانات',
    'privacy.section_7_body': 'نحن نطبق تدابير فنية وتنظيمية مناسبة لحماية بياناتكم، بما في ذلك تشفير SSL/TLS وضوابط الوصول والمراجعات الأمنية الدورية. ومع ذلك، لا توجد طريقة نقل عبر الإنترنت آمنة بنسبة ١٠٠٪.',
    'privacy.contact_title': 'اتصل بنا',
    'privacy.contact_body': 'للاستفسارات المتعلقة بالخصوصية أو لممارسة حقوقكم:',
    'privacy.contact_info': 'أتيليه ريمان — شارع الزهرة، الشارقة، الإمارات — hello@riman.ae',

    // Product
    'product.added': 'تمت الإضافة',
    'product.quick_add': 'إضافة سريعة',
    'product.view_details': 'عرض التفاصيل الكاملة',
    'product.in_wishlist': 'في قائمة الإعجاب',
    'product.add_wishlist': 'أضف لقائمة الإعجاب',
    'product.purchase': 'الشراء',
    'product.rent': 'الإيجار',
    'product.not_found': 'التصميم غير موجود',
    'product.back_to_collection': 'العودة للمجموعة',
    'product.limited_edition': 'إصدار محدود',
    'product.purchase_value': 'قيمة الشراء',
    'product.rental_7day': 'إيجار ٧ أيام متميز',
    'product.rental_includes': 'يشمل التنظيف الجاف والتأمين',
    'product.refundable_deposit': '+ وديعة قابلة للاسترداد',
    'product.select_size_label': 'اختر المقاس',
    'product.size_guide': 'دليل المقاسات',
    'product.book_rental': 'احجز الإيجار',
    'product.add_to_collection': 'أضف للمجموعة',
    'product.reserve_viewing': 'احجزي مشاهدة خاصة',
    'product.error_no_date': 'يرجى اختيار تاريخ الإيجار المفضل.',
    'product.error_no_size': 'يرجى اختيار مقاسك.',
    'product.rental_availability': 'توفر الإيجار',
    'product.fast_booking': 'يُوصى بالحجز السريع',
    'product.select_date_hint': 'اختر تاريخاً للتحقق من توفر الإيجار لمدة ٧ أيام.',
    'product.selected_date': 'التاريخ المختار',
    'product.specifications': 'المواصفات',
    'product.fabric': 'تكوين النسيج',
    'product.designer': 'المصمم',
    'product.style_elements': 'عناصر الأسلوب',
    'product.couture_care': 'رعاية الأزياء الراقية',
    'product.cleaning_included': 'يشمل التنظيف',
    'product.secure_delivery': 'توصيل آمن',
    'product.uae_gcc': 'الإمارات والخليج',
    'product.bespoke_fit': 'ملاءمة حسب الطلب',
    'product.custom_tailoring': 'خياطة مخصصة',
    'product.artistry_essence': 'الحرفية والجوهر',
    'product.client_reflections': 'آراء العميلات',
    'product.leave_reflection': 'اترك رأيك',
    'product.reflection_curated': 'تمت إضافة رأيك بنجاح.',
    'product.write_another': 'اكتب رأياً آخر',
    'product.your_name': 'اسمك',
    'product.your_reflection': 'رأيك',
    'product.submit_review': 'إرسال التقييم',
    'product.curated_for_you': 'منتقى لكِ',
    'product.complementary_picks': 'اختيارات مكمّلة',
    'product.reservation_secured': 'تم تأمين الحجز',
    'product.atelier_moment_booked': 'تم حجز لحظتك في دار ريمان',
    'product.selection': 'الاختيار',
    'product.period_starts': 'تبدأ الفترة',
    'product.rental_policy': 'سياسة الإيجار',
    'product.rental_policy_desc': 'تتضمن فترة الإيجار لمدة ٧ أيام التنظيف الجاف الصديق للبيئة وتأمين الأزياء الراقية. يرجى الإعادة في الموعد المحدد.',
    'product.security_deposit': 'الوديعة الضامنة',
    'product.continue_exploring': 'متابعة الاستكشاف',
    'product.go_to_checkout': 'إتمام الشراء',
    'product.whatsapp': 'واتساب',
    'product.copy_link': 'نسخ الرابط',
    'product.description_intro': 'مصنوعة من أرقى',
    'product.description_mid': 'تجسد جوهر الفخامة العصرية بتصميمها',
    'product.description_outro': '.',
    'product.toast_rental': 'تم حجز الإيجار',
    'product.toast_added': 'تمت الإضافة للحقيبة',
    'product.fitting_title': 'قياس دار الشارقة',
    'product.fitting_desc': 'استأجري بثقة. احجزي جلسة قياس خاصة لمدة ٣٠ دقيقة للتأكد من أن الفستان المختار يناسب جسمك تماماً قبل تاريخ الإيجار.',
    'product.texture_title': 'نسيج الحلم',
    'product.texture_desc': 'مصنوعة من طبقات متعددة من حرير الأورغانزا للحركة الخفيفة اللانهائية المستلهمة من كثبان الشارقة.',
    'product.rating': 'التقييم',
    'product.enter_name': 'أدخل اسمك',
    'product.share_experience': 'شاركينا تجربتك...',
    'product.security_deposit_desc': 'وديعة قابلة للاسترداد بمبلغ',
    'product.will_be_held': 'ستُحجز خلال فترة الإيجار.',
    'product.classic_view': 'عرض كلاسيكي',
    'product.view_3d': 'عرض ثلاثي الأبعاد',
    'product.silhouette': 'القصّة',
    'product.color': 'اللون',
    'product.care_instructions': 'عناية الكوتور',
    'product.care_dry_clean': 'تنظيف جاف متخصص',
    'product.care_dry_clean_desc': 'تنظيف خبراء متخصصين في العناية بالملابس الفاخرة.',
    'product.care_store': 'حقيبة تخزين قابلة للتنفس',
    'product.care_store_desc': 'خزّني في مكان بارد وجاف باستخدام حقيبة التخزين القابلة للتنفس المرفقة.',
    'product.care_handle': 'تعامل بحذر',
    'product.care_handle_desc': 'تجنبيلامس المباشر للعطور ومستحضرات التجميل والإكسسوارات الحادة.',
    'product.care_steam': 'بخار احترافي',
    'product.care_steam_desc': 'استخدمي البخار منخفض الحرارة لإزالة التجاعيد. لا تكوي مباشرة على التطريز.',
    'product.ask_stylist': 'اسألي الخبيرة',
    'product.ask_stylist_desc': 'احجزي استشارة مجانية مع خبراء التصميم لدينا.',
    'product.select_size': 'اختاري المقاس',
    'product.cancel': 'إلغاء',
    'product.quick_shop': 'تسوق سريع',

    // Pricing
    'pricing.from': 'يبدأ من',
    'pricing.rental_period': 'تأجير ٣ أيام',
    'pricing.consultation_note': 'يتم تأكيد السعر النهائي في موعد الاستشارة — يشمل التفصيل والتعديلات.',

    // Badges
    'badge.new': 'جديد مهيب',
    'badge.featured': 'اختيار الدار',
    'badge.gold': 'ذهب خالص',
    'badge.3d': 'عرض ثلاثي الأبعاد',

    // Collection page
    'collection.sort': 'ترتيب',
    'collection.sort_featured': 'مميز',
    'collection.sort_newest': 'الأحدث',
    'collection.sort_price_low': 'السعر: من الأقل',
    'collection.sort_price_high': 'السعر: من الأعلى',
    'collection.colors': 'الألوان',
    'collection.silhouette': 'القصّة',
    'collection.year': 'السنة',
    'collection.filters': 'التصفية',
    'collection.all_silhouettes': 'جميع القصّات',
    'silhouette.A-Line': 'قصة A',
    'silhouette.Ballgown': 'منفوش',
    'silhouette.Mermaid': 'حورية البحر',
    'silhouette.Column': 'قصة مستقيمة',
    'silhouette.Kaftan': 'قفطان',
    'silhouette.One Size': 'إكسسوارات',
    'collection.results': 'نتيجة',
    'collection.clear_all': 'مسح الكل',
    'collection.empty_heading': 'لا توجد تصاميم مطابقة لمرشحاتك.',
    'collection.empty_desc': 'مجموعتنا منتقاة بعناية. جرّب تعديل المرشحات أو استكشف تشكيلتنا الكاملة.',
    'collection.view_all': 'عرض جميع التصاميم',

    // Search
    'search.placeholder': 'ابحث في الدار...',
    'search.results': 'النتائج',
    'search.advanced_filters': 'مرشحات متقدمة',
    'search.empty_heading': 'لا توجد نتائج مطابقة',
    'search.empty_desc': 'لم نتمكن من العثور على ما تبحث عنه. جرّب بحثاً مختلفاً أو تواصل مع مصممينا لطلب خاص.',
    'search.clear': 'مسح الاختيار',
    'search.recommended': 'قد يعجبك أيضاً',

    // Wishlist
    'wishlist.title': 'قائمة الإعجاب',
    'wishlist.subtitle': 'تصاميم أسرت قلبك',
    'wishlist.empty': 'قائمتك فارغة',
    'wishlist.empty_desc': 'ابدأ رحلتك باختيار تصاميمك المفضلة.',
    'wishlist.explore': 'استكشف الدار',
    'wishlist.view': 'عرض',
    'wishlist.add_to_bag': 'أضف للحقيبة',

    // Selection
    'selection.title': 'مختاراتك',
    'selection.subtitle': 'قطع انتظرناها لمشاهدتك الخاصة',
    'selection.empty': 'مختاراتك فارغة',
    'selection.empty_desc': 'احفظي التصاميم التي أسرت قلبك — وستكون جاهزة عند زيارتك.',
    'selection.explore': 'استكشفي الدار',
    'selection.view': 'عرض',
    'selection.add_to_bag': 'أضف للحقيبة',
    'selection.request_viewing': 'طلب مشاهدة خاصة',
    'selection.count': 'قطعة مختارة',
    'selection.share': 'شاركي مختاراتك',
    'selection.link_copied': 'تم نسخ رابط المشاركة',
    'selection.shared_title': 'مختارات منتقاة',
    'selection.shared_subtitle': 'قطع اختيرت لمشاهدة خاصة في أتيليه ريمان',

    // Reviews
    'product.no_reviews_heading': 'لا توجد تجارب بعد',
    'product.no_reviews_desc': 'كوني أول من يشارك تجربتها',
    'product.add_photo': 'أضيفي صورة',
    'product.upload_photo': 'تحميل صورة',
    'product.available': 'متاح',
    'product.fully_booked': 'محجوز بالكامل',

    // Calendar
    'calendar.days': 'أحد,اثنين,ثلاثاء,أربعاء,خميس,جمعة,سبت',
    'calendar.months': 'يناير,فبراير,مارس,أبريل,مايو,يونيو,يوليو,أغسطس,سبتمبر,أكتوبر,نوفمبر,ديسمبر',
    'calendar.available': 'متاح',
    'calendar.booked': 'محجوز',
    'calendar.prev': 'الشهر السابق',
    'calendar.next': 'الشهر التالي',
    'calendar.nextAvailable': 'أقرب تاريخ متاح',
    'calendar.statusAvailable': 'متاح',
    'calendar.statusBooked': 'محجوز',
    'calendar.statusPast': 'ماضٍ',
    'calendar.selectedPrefix': 'المحدد:',
    'calendar.noAvailability': 'لا توجد مواعيد متاحة خلال الأشهر الستة القادمة.',
    'calendar.fallbackNotice': 'تعذّر تحميل التوفر — تُعرض بيانات تقريبية.',
    'calendar.retry': 'إعادة المحاولة',

    // Checkout extras
    'checkout.secured_stripe': 'مؤمَّن عبر Stripe',
    'checkout.secure_order_atelier': 'طلب آمن — الدفع في الأتيليه',
    'checkout.order_failed': 'تعذّر إنشاء الطلب. يرجى المحاولة مرة أخرى.',
    'checkout.country_default': 'الإمارات العربية المتحدة',

    // Payment cancel
    'payment.cancel.title': 'تم إلغاء الدفع',
    'payment.cancel.body': 'لم يتم خصم أي مبالغ، ولم يتم إنشاء طلبك.',
    'payment.cancel.return_checkout': 'العودة إلى الحقيبة',
    'payment.cancel.continue_browsing': 'متابعة التصفح',

    // Wedding checklist
    'wedding.checklist.eyebrow': 'الطريق إلى نعم',
    'wedding.checklist.title': 'قائمة التخطيط للزفاف',
    'wedding.checklist.m12': 'قبل 12 شهرًا',
    'wedding.checklist.t12': 'حددي تاريخ الزفاف والمكان.',
    'wedding.checklist.m11': 'قبل 11 شهرًا',
    'wedding.checklist.t11': 'احجزي استشارتك الأولى في أتيليه ريمان.',
    'wedding.checklist.m9': 'قبل 9 أشهر',
    'wedding.checklist.t9': 'حسدي اختيار القصة والقماش.',
    'wedding.checklist.m6': 'قبل 6 أشهر',
    'wedding.checklist.t6': 'أول بروفة وتفاصيل التطريز.',
    'wedding.checklist.m3': 'قبل 3 أشهر',
    'wedding.checklist.t3': 'استكملي الإطلالة بالطرح وإكسسوارات الرأس.',
    'wedding.checklist.m1': 'قبل شهر',
    'wedding.checklist.t1': 'البروفة النهائية واستلام الفستان.',

    // Wedding timeline
    'wedding.timeline.title': 'الجدول الزمني للزفاف',
    'wedding.timeline.subtitle': 'نرسم معكِ الطريق إلى نعم',
    'wedding.timeline.return_home': 'العودة إلى الرئيسية',

    // Newsletter modal
    'newsletter.title': 'دائرة الأتيليه',
    'newsletter.body': 'انضمي للحصول على عروض حصرية لمجموعات الزفاف الجديدة ودعوات المعاينات الخاصة في الشارقة.',
    'newsletter.email_placeholder': 'البريد الإلكتروني',
    'newsletter.email_aria': 'البريد الإلكتروني',
    'newsletter.cta': 'انضمي إلى الجمعية',

    // Cookie banner
    'cookies.heading': 'الخصوصية والأناقة',
    'cookies.body': 'نستخدم ملفات تعريف الارتباط لتوفير تجربة أتيليه مخصصة لكِ.',
    'cookies.learn': 'اعرفي المزيد',
    'cookies.accept': 'الموافقة والاستكشاف',
    'cookies.reject': 'رفض',

    // Errors & common
    'errors.tech_title': 'لحظة تقنية',
    'errors.tech_body': 'أتيليهنا الرقمي يمر بوقفة قصيرة. يرجى تحديث الصفحة أو العودة إلى مجموعتنا الرئيسية.',
    'errors.return_atelier': 'العودة إلى الأتيليه',
    'common.close': 'إغلاق',
    'common.retry': 'إعادة المحاولة',
    'threed.initializing': 'جارٍ تحميل التفاصيل ثلاثية الأبعاد',

    // Toasts & fallbacks
    'product.toast_suffix_rental': 'تم حجز الإيجار',
    'product.toast_suffix_added': 'أُضيف إلى مجموعتك',
    'product.fabric_default': 'مزيج فاخر',
    'auth.profile_missing_title': 'لم يتم العثور على الملف الشخصي',
    'auth.load_fail_title': 'تعذر تحميل الحساب',
    'auth.limited_msg': 'قد تكون بعض الميزات محدودة.',
    'threed.unavailable': 'عارض المجسمات غير متاح',
    'threed.reset_view': 'إعادة ضبط العرض',
    'common.whatsapp_label': 'تواصلي معنا عبر واتساب',
    'wishlist.remove_aria': 'إزالة من المختارات',

    // Checkout
    'checkout.empty': 'حقيبتك فارغة',
    'checkout.empty_desc': 'يرجى اختيار القطع من مجموعتنا أولاً.',
    'checkout.explore': 'استكشف المجموعة',
    'checkout.step_identity': 'الهوية',
    'checkout.step_logistics': 'التوصيل',
    'checkout.step_confirm': 'التأكيد',
    'checkout.personal_details': 'البيانات الشخصية',
    'checkout.delivery_info': 'معلومات التوصيل',
    'checkout.review': 'المراجعة والتأكيد',
    'checkout.first_name': 'الاسم الأول',
    'checkout.last_name': 'اسم العائلة',
    'checkout.email': 'البريد الإلكتروني',
    'checkout.phone': 'رقم الهاتف',
    'checkout.address': 'العنوان',
    'checkout.city': 'المدينة',
    'checkout.country': 'الدولة',
    'checkout.continue_logistics': 'متابعة إلى التوصيل',
    'checkout.review_order': 'مراجعة الطلب',
    'checkout.previous': 'السابق',
    'checkout.your_details': 'بياناتك',
    'checkout.your_selections': 'اختياراتك',
    'checkout.subtotal': 'المجموع الفرعي',
    'checkout.delivery': 'توصيل الدار',
    'checkout.complimentary': 'مجاني',
    'checkout.vat': 'ضريبة القيمة المضافة (٥٪)',
    'checkout.included': 'شامل',
    'checkout.total': 'الإجمالي',
    'checkout.bag_summary': 'ملخص الحقيبة',
    'checkout.order_notes': 'ملاحظات الطلب (اختياري)',
    'checkout.notes_placeholder': 'أي طلبات خاصة أو مقاسات...',
    'checkout.payment_method': 'طريقة الدفع',
    'checkout.pay_atelier': 'احجزي في الدار',
    'checkout.pay_atelier_desc': 'بدون دفع إلكتروني — صاحبة الدار تؤكد كل طلب عبر واتساب. التوصيل لجميع دول العالم.',
    'checkout.pay_online': 'ادفع عبر الإنترنت',
    'checkout.pay_online_desc': 'دفع آمن بالبطاقة عبر سترايب — فيزا وماستركارد مقبولة. التوصيل لجميع دول العالم.',
    'checkout.secure_online': 'دفع آمن عبر الإنترنت',
    'checkout.secure_online_desc': 'سيتم خصم المبلغ كاملاً من بطاقتك. ثم سيقوم فريقنا بترتيب جلسة قياس خاصة وتوصيل من دارنا بالشارقة.',
    'checkout.instore_payment': 'الدفع والقياس في الدار',
    'checkout.instore_desc': 'سيؤكد فريقنا طلبك ويرتب جلسة قياس خاصة. يُكمل الدفع في دارنا بالشارقة عند الاستلام أو التوصيل.',
    'checkout.confirm_order': 'تأكيد الطلب',
    'checkout.order_received': 'تم استلام الطلب',
    'checkout.order_preparing': 'يتم الآن تجهيز طلبيتك في دارنا.',
    'checkout.confirmation_email': 'سيتم إرسال التأكيد إلى',
    'checkout.contact_24h': 'سيتواصل فريقنا معك خلال ٢٤ ساعة لترتيب القياس والتوصيل وتفاصيل الدفع.',
    'checkout.view_dashboard': 'عرض لوحتي',
    'checkout.required': 'مطلوب',
    'checkout.size': 'المقاس',
    'checkout.date': 'التاريخ',
    'checkout.qty': 'الكمية',
    'checkout.secure_payment': 'دفع آمن',
    'checkout.returns_policy': 'إرجاع خلال ١٤ يوم',
    'checkout.whatsapp_support': 'دعم واتساب',
    'checkout.order_summary': 'ملخص الطلب',
    'checkout.show_summary': 'عرض ملخص الطلب',
    'checkout.hide_summary': 'إخفاء ملخص الطلب',
    'checkout.items_count': '{count} قطع',
    'checkout.back_to_shop': 'العودة للمتجر',
    'checkout.val_email': 'يرجى إدخال بريد إلكتروني صحيح',
    'checkout.val_phone': 'يرجى إدخال رقم هاتف صحيح',
    'checkout.val_name': 'يرجى إدخال اسمك',
    'checkout.val_address': 'يرجى إدخال عنوانك',
    'checkout.val_city': 'يرجى إدخال مدينتك',
    'checkout.val_country': 'يرجى اختيار بلدك',
    'checkout.name_label': 'الاسم',

    // Payment
    'payment.verifying': 'جارٍ تأكيد الدفع',
    'payment.please_wait': 'الرجاء الانتظار قليلاً...',
    'payment.success_title': 'تم الدفع بنجاح',
    'payment.success_sub': 'لقد استلمنا طلبك.',
    'payment.sent_to': 'تم إرسال التأكيد إلى',
    'payment.success_body': 'سيتواصل معك فريقنا خلال ٢٤ ساعة لترتيب التفصيل والتوصيل.',
    'payment.dashboard': 'لوحة حسابي',
    'payment.error_title': 'لم يتم تأكيد الدفع',
    'payment.error_body': 'الرجاء التواصل مع الدار لتأكيد طلبك.',
    'payment.contact': 'تواصلي معنا',
    'payment.home': 'العودة للرئيسية',

    // Auth
    'auth.signin': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.welcome_back': 'مرحباً بعودتك إلى الدار',
    'auth.join': 'انضمي إلى مجتمع ريمان',
    'auth.enter_atelier': 'دخول الدار',
    'auth.create_profile': 'إنشاء الملف',
    'auth.authenticated': 'تم المصادقة',
    'auth.redirecting': 'جاري التحويل إلى ملفك...',
    'auth.full_name': 'الاسم الكامل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name_placeholder': 'مثال: سارة منصور',
    'auth.email_placeholder': 'name@example.com',
    'auth.password_placeholder': '٦ أحرف على الأقل',
    'auth.no_account': 'ليس لديك حساب؟ أنشئ واحداً',
    'auth.has_account': 'لديك حساب؟ سجّل الدخول',
    'auth.clear_session': 'مشكلة في الاتصال؟ مسح الجلسة',
    'auth.error_email': 'يرجى إدخال بريدك الإلكتروني.',
    'auth.error_password': 'كلمة المرور يجب أن تكون ٦ أحرف على الأقل.',
    'auth.error_name': 'يرجى إدخال اسمك.',

    // Appointment
    'appointment.heading': 'استشارة خاصة',
    'appointment.desc': 'اختبر دار ريمان بنفسك. سيقودك كبار المصممين عبر مجموعتنا ويساعدونك في العثور على فستان أحلامك.',
    'appointment.step_details': 'البيانات',
    'appointment.step_schedule': 'الموعد',
    'appointment.step_confirm': 'التأكيد',
    'appointment.your_details': 'بياناتك',
    'appointment.choose_datetime': 'اختر التاريخ والوقت',
    'appointment.review_confirm': 'المراجعة والتأكيد',
    'appointment.full_name': 'الاسم الكامل *',
    'appointment.email': 'البريد الإلكتروني *',
    'appointment.phone': 'رقم الهاتف *',
    'appointment.service_type': 'نوع الخدمة *',
    'appointment.select_service': 'اختر خدمة',
    'appointment.your_gowns': 'قطعك المختارة',
    'appointment.select_date': 'اختر التاريخ *',
    'appointment.select_time': 'اختر الوقت *',
    'appointment.special_requests': 'طلبات خاصة (اختياري)',
    'appointment.notes_placeholder': 'أي شيء تودّ أن نجهزه لزيارتك...',
    'appointment.continue_scheduling': 'متابعة إلى تحديد الموعد',
    'appointment.review_booking': 'مراجعة الحجز',
    'appointment.confirm_booking': 'تأكيد الحجز',
    'appointment.confirming': 'جاري التأكيد...',
    'appointment.back': 'رجوع',
    'appointment.name': 'الاسم',
    'appointment.email_label': 'البريد الإلكتروني',
    'appointment.phone_label': 'الهاتف',
    'appointment.service_label': 'الخدمة',
    'appointment.date_label': 'التاريخ',
    'appointment.time_label': 'الوقت',
    'appointment.booked': 'تم تأكيد الحجز',
    'appointment.thank_you': 'شكراً لك',
    'appointment.appointment_booked_for': 'محجوز في',
    'appointment.at': 'في',
    'appointment.confirmation_sent': 'سيتم إرسال التأكيد إلى',
    'appointment.our_team_reach': 'سيتواصل فريقنا لتأكيد التفاصيل.',
    'appointment.explore_collection': 'استكشف المجموعة',
    'appointment.whatsapp_continue': 'تابعينا على واتساب',
    'appointment.error_name': 'يرجى إدخال اسمك',
    'appointment.error_email': 'يرجى إدخال بريد إلكتروني صحيح',
    'appointment.error_phone': 'يرجى إدخال رقم هاتفك',
    'appointment.error_service': 'يرجى اختيار نوع الخدمة',
    'appointment.error_date': 'يرجى اختيار تاريخ',
    'appointment.error_time': 'يرجى اختيار وقت',
    'appointment.fill_all': 'يرجى ملء جميع الحقول المطلوبة',
    'appointment.select_date_time': 'يرجى اختيار التاريخ والوقت',
    'appointment.something_wrong': 'حدث خطأ. يرجى المحاولة مرة أخرى أو التواصل معنا مباشرة عبر واتساب.',
    'appointment.atelier_hours': 'يومياً: ١١ صباحاً – ٩ مساءً  |  الجمعة: بعد الصلاة – ٩ مساءً',
    'appointment.whatsapp_help': 'تحتاج مساعدة؟ تواصل عبر واتساب',

    // Footer
    'footer.about': 'نصنع أرقى الفساتين في الشارقة. نعيد تصور تراث الأناقة للملهمة العصرية، حيث يحمل كل خيط قصة من الجوهر الملكي.',
    'footer.location': 'شارع الزهراء، الشارقة، الإمارات',
    'footer.ascend': 'الصعود للأعلى',
    'footer.rights': 'صُنع في الشارقة.',
    'footer.privacy': 'الخصوصية',
    'footer.legal': 'الشروط',
    'footer.newsletter_title': 'رسالة الدار',
    'footer.newsletter_text': 'انضمي إلى دائرتنا الخاصة لمعاينات حصرية للمجموعات ورؤى الأزياء الراقية.',
    'footer.newsletter_placeholder': 'بريدك الإلكتروني',
    'footer.submitted': 'تم الإرسال',
    'footer.collections': 'المجموعات',
    'footer.services': 'الخدمات',
    'footer.atelier_location': 'موقع الدار',
    'footer.consultation': 'استشارة خاصة',
    'footer.links': 'روابط سريعة',
    'footer.follow': 'تابعنا',
    'footer.newsletter': 'النشرة',
    'footer.bespoke_fitting': 'قياس خاص',
    'footer.aura_consultation': 'استشارة الأناقة',
    'footer.bridal_concierge': 'كنسيرج العرائس',
    'footer.assistance': 'المساعدة',

    // Forms
    'form.name': 'الاسم الكامل',
    'form.email': 'البريد الإلكتروني',
    'form.message': 'الرسالة',
    'form.submit': 'إرسال الاستفسار',

    // Profile
    'profile.dashboard': 'لوحتي',
    'profile.welcome': 'مرحباً بعودتك إلى مجتمع ريمان',
    'profile.member': 'عضو',
    'profile.total_investments': 'إجمالي الاستثمارات',
    'profile.active_rentals': 'الإيجارات النشطة',
    'profile.orders_placed': 'الطلبات',
    'profile.recent_engagements': 'أحدث الطلبات',
    'profile.orders': 'الطلبات والإيجارات',
    'profile.appointments': 'المواعيد',
    'profile.preferences': 'التفضيلات',
    'profile.sign_out': 'تسجيل الخروج',
    'profile.no_orders': 'لا توجد طلبات بعد. ابدأ رحلتك معنا.',
    'profile.backend_not_connected': 'الخادم غير متصل. سجل الطلبات غير متاح.',
    'profile.rental_booking': 'حجز إيجار',
    'profile.combined_order': 'طلب مركّب',
    'profile.purchase_order': 'شراء',
    'profile.explore_new': 'استكشف المجموعات الجديدة',

    // Alterations
    'alt.hero_title': 'فن الخياطة المخصصة',
    'alt.hero_desc': 'فساتين جميلة بقدر جمال مقاسها. خياطونا الرئيسيون في الشارقة متخصصون في إتقان أكثر الخطوط تعقيداً في العالم.',
    'alt.book_fitting': 'احجز قياسك',
    'alt.step1_title': 'الاستشارة الأولية',
    'alt.step1_desc': 'جلسة خاصة لمدة 45 دقيقة لتقييم الخطوط ومناقشة رؤيتك.',
    'alt.step2_title': 'التثبيت والنحت',
    'alt.step2_desc': 'خياطنا الرئيسي يقوم شخصياً بتثبيت القماش لضمان مقاس مثالي.',
    'alt.step3_title': 'تنقيح التفاصيل',
    'alt.step3_desc': 'إنهاء الأطراف يدوياً وإعادة الحبيبات وتعزيز الهيكل الداخلي.',
    'alt.step4_title': 'الكشف النهائي',
    'alt.step4_desc': 'القياس النهائي لضمان الراحة والحركة والكمال.',
    'alt.service_bridal_title': 'كمال الزفاف',
    'alt.service_bridal_desc': 'حصرياً لعرائس ريمان والفساتين الخارجية. تعديلات معقدة على الصدر وتقصير الأطوال المتعددة.',
    'alt.service_evening_title': 'إعادة بناء السهرة',
    'alt.service_evening_desc': 'تحويل الفخامة الجاهزة إلى قطع مخصصة. تعديلات الرقبة وإضافة الأكمام.',
    'alt.service_urgent_title': 'تنقيح عاجل',
    'alt.service_urgent_desc': 'تعديلات لحظة الأخيرة للحفلات والمناسبات. حسب التوفر في مشغلنا بالشارقة.',
    'alt.fitting_journey': 'رحلة القياس',
    'alt.cta_heading': 'هل تستحق فستانك الأفضل؟',
    'alt.cta_desc': 'نقبل عدداً محدوداً من التعديلات الخارجية شهرياً للحفاظ على معايير جودتنا. سواء كان تراثاً عائلياً أو قطعة حديثة، نتعامل مع كل خيط بالاحترام الذي يستحقه.',
    'alt.available': 'متاح من الاثنين إلى الخميس',
    'alt.guarantee': 'ضمان 3 قياسات',
    'alt.inquire': 'استفسر عن التوفر',

    // Quiz
    'quiz.q1': 'أين تتخيل احتفالك؟',
    'quiz.q1_opt1': 'قاعة كبار الشخصيات في الشارقة',
    'quiz.q1_opt2': 'واحة صحراوية تحت النجوم',
    'quiz.q1_opt3': 'فيلا ساحلية خاصة',
    'quiz.q1_opt4': 'تراس أفق عصري',
    'quiz.q2': 'أي خط يتحدث إلى روحك؟',
    'quiz.q2_opt1': 'فستان زفاف مهيب',
    'quiz.q2_opt2': 'حورية البحر أنيقة',
    'quiz.q2_opt3': 'أخطي أثري',
    'quiz.q2_opt4': 'فستان سlip عصري',
    'quiz.q3': 'أي ملمس يشبهك أكثر؟',
    'quiz.q3_opt1': 'دانتيل يدوي معقد',
    'quiz.q3_opt2': 'حرير ميكادو معماري',
    'quiz.q3_opt3': 'شيفون وتويل الانسيابي',
    'quiz.q3_opt4': 'ساتان لامع ولآلئ',
    'quiz.q4': 'ما هو "الهالة" المحدد ليومك؟',
    'quiz.q4_opt1': 'تراث خالد',
    'quiz.q4_opt2': 'طليع جريء',
    'quiz.q4_opt3': 'رومانسية ناعمة',
    'quiz.q4_opt4': 'بساطة راقية',
    'quiz.error': 'مموّلونا مشغولون حالياً. يرجى المحاولة مرة أخرى أو زيارتنا شخصياً.',
    'quiz.title': 'سجل الأناقة',
    'quiz.subtitle': 'اكتشف هالة ريمان',
    'quiz.loading': 'التشاور مع خياطينا الافتراضيين...',
    'quiz.your_aesthetic': 'جمالياتك',
    'quiz.stylist_tip': 'نصيحة المصمم',
    'quiz.view_recs': 'عرض التوصيات',
    'quiz.retry': 'إعادة التجربة',
    'quiz.try_again': 'حاول مرة أخرى',
    'quiz.progress': 'سؤال',
    'quiz.your_matches': 'مطابقاتك المثالية',
    'quiz.no_matches': 'دعنا نساعدك في إيجاد القطعة',
    'quiz.based_on_answers': 'بناءً على إجاباتك، نعتقد أنك ستحب هذه التصاميم.',
    'quiz.browse_collection': 'تصفح مجموعتنا المختارة لإيجاد قطعتك المثالية.',
    'quiz.try_different': 'جرّب خيارات مختلفة لاكتشاف المزيد من الأنماط.',
    'quiz.view_all': 'عرض المجموعة الكاملة',

    // FAQ
    'faq.category_rental': 'خدمات الإيجار',
    'faq.q_rental_1': 'ما مدة الإيجار المعيارية؟',
    'faq.a_rental_1': 'فترة الإيجار المعيارية "التوظيف المتميز" هي 7 أيام. يمكن ترتيب الامتدادات مقابل رسوم إضافية، حسب التوفر. نوصي بالحجز قبل 4 أسابيع على الأقل.',
    'faq.q_rental_2': 'هل التظيف الجاف مشمول في سعر الإيجار؟',
    'faq.a_rental_2': 'نعم، كل إيجار ريمان يشمل تظيفاً جافاً مهنياً صديقاً للبيئة قبل وبعد حدثك.',
    'faq.q_rental_3': 'ماذا يحدث إذا تلفت قطعة الإيجار بالخطأ؟',
    'faq.a_rental_3': 'جميع الإيجارات تشمل "تأمين الكوتور" الأساسي الذي يغطي الحوادث البسيطة.',
    'faq.category_bespoke': 'الخياطة المخصصة والتعديلات',
    'faq.q_bespoke_1': 'هل أحتاج إلى موعد للقياس؟',
    'faq.a_bespoke_1': 'نعم، جميع القياسات في مشغلنا بالشارقة بموعد صارم لضمان حصولك على اهتمامنا الكامل.',
    'faq.q_bespoke_2': 'هل يمكنكم تعديل فساتين لم تُشتر من ريمان؟',
    'faq.a_bespoke_2': 'نقبل عدداً محدوداً من التعديلات الخارجية شهرياً.',
    'faq.category_shipping': 'الشحن والإرجاع',
    'faq.q_shipping_1': 'هل تشحنون دولياً؟',
    'faq.a_shipping_1': 'نعم، نشحن عبر الإمارات والخليج. الشحن الدولي متاح عند الطلب.',
    'faq.q_shipping_2': 'ما سياسة الإرجاع للمشتريات؟',
    'faq.a_shipping_2': 'نقدم سياسة إرجاع لمدة 14 يوماً للعناصر غير الم mặcة وبحالتها الأصلية.',
    'faq.search_placeholder': 'كيف يمكننا مساعدتك اليوم؟',
    'faq.still_unsure': 'ما زلت غير متأكد؟',
    'faq.still_unsure_desc': 'مكتب خدماتنا متاح من 9 صباحاً حتى 9 مساءً بتوقيت الخليج.',
    'faq.submit_inquiry': 'إرسال استفسار',
    'faq.whatsapp_expert': 'خبير واتساب',
    'faq.title': 'concierge الخدمة',

    // Size Guide
    'size_guide.title': 'دليل المقاسات',
    'size_guide.desc': 'جميع القياسات بالسنتيمتر. للحصول على المقاس المثالي، نوصي بطلب قياسات من متخصص.',
    'size_guide.size': 'المقاس',
    'size_guide.bust': 'الصدر',
    'size_guide.waist': 'الخصر',
    'size_guide.hips': 'الأرداف',
    'size_guide.cm': 'سم',
    'size_guide.how_to_measure': 'كيف تقيس',
    'size_guide.measure_bust': 'الصدر:',
    'size_guide.measure_bust_desc': 'قيس حول أكمل جزء من صدرك.',
    'size_guide.measure_waist': 'الخصر:',
    'size_guide.measure_waist_desc': 'قيس حول أضيق جزء من خصرك الطبيعي.',
    'size_guide.measure_hips': 'الأرداف:',
    'size_guide.measure_hips_desc': 'قيس حول أكمل جزء من أردافك.',
    'size_guide.alterations_title': 'التعديلات المخصصة:',
    'size_guide.alterations_desc': 'كل مشتريات ريمان تشمل تعديلات مجانية في مشغلنا بالشارقة.',

    // About — narratives, quote, roles, stats
    'about.narrative_1': 'تأسست في قلب الشارقة، ولدت ريمان فاشن من شغف بالحفاظ على الحرفية التقليدية مع تبني التصميم المعاصر. مشغلنا هو قمة الفخامة، حيث يُنسج كل خيط بقصد ملكي.',
    'about.narrative_2': 'اليوم، نقف كوجهة أولى لمن يبحث عن أكثر من مجرد فستان. كل قطعة في مجموعتنا شاهدة على الليالي الطويلة على طاولة الخياطة، الحرير الإيطالي المستورد، وفن تطبيق الدانتيل الفرنسي الرقيق.',
    'about.quote': 'لا نبيع الفساتين فحسب، بل نبتكر اللحظات التي سيُتحدث عنها للأجيال.',
    'about.quote_author': '— سارة منصور، المؤسسة',
    'about.pillars': 'ركائز المشغل',
    'about.visionaries': 'المبدعون',
    'about.collective': 'جماعة ريمان',
    'about.role_founder': 'مؤسسة ومصممة رئيسية',
    'about.role_embroidery': 'رئيسة التطريز',
    'about.role_jewelry': 'مسؤولة المجوهرات الذهبية',
    'about.stat_beads': 'حبيبات مُضَمّة يدوياً لكل فستان',
    'about.stat_runways': 'أزياء عالمية تميزت بها',

    // Instagram
    'instagram.title': 'هالة ريمان',
    'instagram.follow': 'تابعنا @rimanfashion',
    'instagram.view_aura': 'عرض الهالة',
    'instagram.explore': 'استكشف المعرض الكامل',

    // Contact
    'contact.narrative': 'ندعوك لتجربة مجموعاتنا شخصياً. مشغلنا بالشارقة يوفر بيئة خاصة وهادئة لاستكشاف رؤيتك لحفل زفافك وقطع المجوهرات الخاصة بنا.',
    'contact.location': 'الموقع',
    'contact.location_addr': 'شارع الزهراء، الشارقة، الإمارات العربية المتحدة',
    'contact.contact_details': 'بيانات الاتصال',
    'contact.phone_email': 'الهاتف: ٧٩٧٣٠٥٥٣+ | البريد: boutique@riman.ae',
    'contact.hours': 'ساعات العمل',
    'contact.hours_detail': 'يومياً: ١١ صباحاً - ٩ مساءً | الجمعة: بعد الصلاة - ٩ مساءً',
    'contact.special_note': 'ملاحظة خاصة',
    'contact.special_note_desc': 'زيارات الجمعة مخصصة للاستشارات الخاصة وبحجز مسبق فقط.',
    'contact.request_consultation': 'طلب استشارة',
    'contact.inquiry_type': 'نوع الاستفسار',
    'contact.bridal_consultation': 'استشارة زفاف',
    'contact.evening_inquiry': 'استفسار فساتين سهرة',
    'contact.rental_booking': 'حجز إيجار',
    'contact.bespoke_alterations': 'تعديلات مخصصة',
    'contact.vision_prefs': 'الرؤية والتفضيلات',
    'contact.vision_placeholder': 'أخبرنا عن حدثك، المجموعة المفضلة، أو الخط...',
    'contact.success_title': 'تم إرسال الطلب بنجاح',
    'contact.success_desc': 'سيرد فريقنا خلال 24 ساعة.',
    'contact.write_another': 'كتابة طلب آخر',
    'contact.val_name': 'يجب أن يكون الاسم حرفين على الأقل',
    'contact.val_email': 'بريد إلكتروني غير صالح',
    'contact.val_phone': 'رقم هاتف صالح مطلوب',
    'contact.val_details': 'يرجى تقديم مزيد من التفاصيل حول استفسارك',
    'contact.toast_demo_title': 'وضع العرض التوضيحي',
    'contact.toast_demo_msg': 'هذا النموذج غير متصل بخادم. لم يتم حفظ رسالتك.',
    'contact.toast_sent_title': 'تم الإرسال',
    'contact.toast_sent_msg': 'سيرد فريقنا خلال 24 ساعة.',

    // Header
    'header.collections': 'المجموعات',
    'header.atelier': 'المشغل',
    'header.services': 'الخدمات',
    'header.tagline': 'الشارقة، الإمارات | مشغل زفاف رائد',
    'header.menu_open': 'افتح قائمة التنقل',
    'header.menu_close': 'أغلق القائمة',
    'header.switch_to_ar': 'التبديل إلى العربية',
    'header.switch_to_en': 'التبديل إلى الإنجليزية',
    'header.search': 'بحث',
    'header.style_quiz': 'استشارة الأناقة',
    'header.your_selection': 'قائمة الإعجاب',
    'header.account': 'حسابي',
    'header.bag': 'حقيبة التسوق',
    'notfound.title': 'خارج مجموعتنا',
    'notfound.desc': 'الصفحة التي تبحثين عنها غير موجودة أو تم نقلها إلى موقع جديد داخل دارنا.',
    'notfound.home': 'العودة للرئيسية',
    'notfound.browse': 'تصفح المجموعة',
    'notfound.contact': 'تواصل مع الدار',
    'footer.newsletter_submit': 'الاشتراك في النشرة',

    // Footer
    'footer.fine_jewelry': 'مجوهرات فاخرة',
    'footer.valid_email': 'يرجى إدخال بريد إلكتروني صالح',

    // Gallery
    'gallery.title': 'تأمل بصري',
    'gallery.subtitle': 'معرض المشغل',
    'gallery.description': 'مجموعة مختارة من أجمل لحظاتنا',
    'gallery.filter_all': 'الكل',
    'gallery.filter_bridal': 'عرايس',
    'gallery.filter_evening': 'سهر',
    'gallery.filter_jewelry': 'مجوهرات',
    'gallery.filter_bts': 'خلف الكواليس',
    'gallery.filter_clients': 'قصص العملاء',
    'gallery.load_more': 'المزيد',
    'gallery.view_full': 'عرض المعرض كاملاً',
    'gallery.back': 'العودة للمعرض',
    'gallery.no_items': 'لا توجد عناصر في هذه الفئة',
    'gallery.admin_title': 'إدارة المعرض',
    'gallery.admin_upload': 'رفع وسائط',
    'gallery.admin_edit': 'تعديل العنصر',
    'gallery.admin_delete': 'حذف العنصر',
    'gallery.admin_featured': 'مميز',
    'gallery.admin_sort': 'ترتيب العرض',
  }
};

const fallbackValue: LanguageContextType = {
  language: 'en',
  isRtl: false,
  setLanguage: () => {},
  t: (key: string) => translations.en[key] || key,
};

const LanguageContext = createContext<LanguageContextType>(fallbackValue);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('riman_lang') as Language) || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('riman_lang', language);
    document.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const isRtl = language === 'ar';
  
  const t = (key: string) => {
    return translations[language][key] || translations.en[key] || key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRtl, t }}>
      <div className={isRtl ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
